const GEM_DATA = {
  classes: [
    { id: "witch", name: "마녀" },
    { id: "shadow", name: "그림자" },
    { id: "ranger", name: "레인저" },
    { id: "duelist", name: "결투사" },
    { id: "marauder", name: "야만전사" },
    { id: "templar", name: "템플러" },
    { id: "scion", name: "사이온" },
  ],
  gems: [
    { id: "absolution", name: "면죄", type: "skill", color: "str" },
    { id: "added_cold_damage_support", name: "냉기 피해 추가 보조", type: "support", color: "dex" },
    { id: "added_fire_damage_support", name: "화염 피해 추가 보조", type: "support", color: "str" },
    { id: "added_lightning_damage_support", name: "번개 피해 추가 보조", type: "support", color: "int" },
    { id: "additional_accuracy_support", name: "정확도 추가 보조", type: "support", color: "dex" },
    { id: "alchemists_mark", name: "연금술사의 징표", type: "skill", color: "dex" },
    { id: "ambush", name: "매복", type: "skill", color: "dex" },
    { id: "ancestral_call_support", name: "선대의 부름 보조", type: "support", color: "str" },
    { id: "ancestral_cry", name: "선대의 함성", type: "skill", color: "str" },
    { id: "anger", name: "분노", type: "skill", color: "str" },
    { id: "animate_guardian", name: "수호자 기동", type: "skill", color: "str" },
    { id: "animate_weapon", name: "무기 기동", type: "skill", color: "dex" },
    { id: "arc", name: "연쇄 번개", type: "skill", color: "int" },
    { id: "arcane_cloak", name: "비전의 망토", type: "skill", color: "int" },
    { id: "arcane_surge_support", name: "비전 쇄도 보조", type: "support", color: "int" },
    { id: "arcanist_brand", name: "신비학자 낙인", type: "skill", color: "int" },
    { id: "archmage_support", name: "대마법사 보조", type: "support", color: "int" },
    { id: "arctic_armour", name: "한파 방어", type: "skill", color: "dex" },
    { id: "armageddon_brand", name: "종말의 낙인", type: "skill", color: "int" },
    { id: "arrogance_support", name: "오만 보조", type: "support", color: "str" },
    { id: "arrow_nova_support", name: "화살 산개 보조", type: "support", color: "dex" },
    { id: "artillery_ballista", name: "포대 쇠뇌", type: "skill", color: "dex" },
    { id: "assassins_mark", name: "암살자의 징표", type: "skill", color: "int" },
    { id: "autoexertion", name: "자동 전력", type: "skill", color: "str" },
    { id: "automation", name: "자동화", type: "skill", color: "int" },
    { id: "ball_lightning", name: "구형 번개", type: "skill", color: "int" },
    { id: "ballista_totem_support", name: "쇠뇌 토템 보조", type: "support", color: "str" },
    { id: "bane", name: "파멸", type: "skill", color: "int" },
    { id: "barrage", name: "연발 사격", type: "skill", color: "dex" },
    { id: "barrage_support", name: "연발 사격 보조", type: "support", color: "dex" },
    { id: "battlemages_cry", name: "전투마법사의 함성", type: "skill", color: "str" },
    { id: "bear_trap", name: "곰 덫", type: "skill", color: "dex" },
    { id: "behead_support", name: "참수 보조", type: "support", color: "str" },
    { id: "berserk", name: "광폭", type: "skill", color: "str" },
    { id: "blade_blast", name: "칼날 폭격", type: "skill", color: "dex" },
    { id: "blade_flurry", name: "질풍의 칼날", type: "skill", color: "dex" },
    { id: "blade_trap", name: "칼날 덫", type: "skill", color: "dex" },
    { id: "blade_vortex", name: "칼날 소용돌이", type: "skill", color: "dex" },
    { id: "bladefall", name: "칼날비", type: "skill", color: "dex" },
    { id: "bladestorm", name: "칼날 폭풍", type: "skill", color: "str" },
    { id: "blasphemy_support", name: "신성 모독 보조", type: "support", color: "int" },
    { id: "blast_rain", name: "폭발 화살비", type: "skill", color: "dex" },
    { id: "blastchain_mine_support", name: "연쇄 폭발 지뢰 보조", type: "support", color: "int" },
    { id: "blazing_salvo", name: "맹렬한 포격", type: "skill", color: "int" },
    { id: "blight", name: "황폐", type: "skill", color: "int" },
    { id: "blind_support", name: "실명 보조", type: "support", color: "dex" },
    { id: "blink_arrow", name: "점멸 화살", type: "skill", color: "dex" },
    { id: "blood_and_sand", name: "피와 모래", type: "skill", color: "str" },
    { id: "blood_rage", name: "피의 격노", type: "skill", color: "dex" },
    { id: "bloodlust_support", name: "유혈 충동 보조", type: "support", color: "str" },
    { id: "bloodthirst_support", name: "피의 갈증 보조", type: "support", color: "str" },
    { id: "bodyswap", name: "신체 전환", type: "skill", color: "int" },
    { id: "bone_offering", name: "뼈 공물", type: "skill", color: "int" },
    { id: "bonechill_support", name: "사무치는 한기 보조", type: "support", color: "int" },
    { id: "boneshatter", name: "뼈 박살", type: "skill", color: "str" },
    { id: "brand_recall", name: "낙인 소환", type: "skill", color: "int" },
    { id: "brutality_support", name: "포악함 보조", type: "support", color: "str" },
    { id: "burning_arrow", name: "불타는 화살", type: "skill", color: "dex" },
    { id: "burning_damage_support", name: "화상 피해 보조", type: "support", color: "str" },
    { id: "cast_on_critical_strike_support", name: "치명타 시 시전 보조", type: "support", color: "dex" },
    { id: "cast_on_death_support", name: "사망 시 시전 보조", type: "support", color: "dex" },
    { id: "cast_on_melee_kill_support", name: "근접 처치 시 시전 보조", type: "support", color: "str" },
    { id: "cast_when_damage_taken_support", name: "피격 시 시전 보조", type: "support", color: "str" },
    { id: "cast_when_stunned_support", name: "기절 시 시전 보조", type: "support", color: "int" },
    { id: "cast_while_channelling_support", name: "집중 유지 중 시전 보조", type: "support", color: "int" },
    { id: "caustic_arrow", name: "부식성 화살", type: "skill", color: "dex" },
    { id: "chain_hook", name: "사슬 갈고리", type: "skill", color: "str" },
    { id: "chain_support", name: "연쇄 보조", type: "support", color: "dex" },
    { id: "chance_to_bleed_support", name: "출혈 확률 보조", type: "support", color: "str" },
    { id: "chance_to_flee_support", name: "도망칠 확률 보조", type: "support", color: "dex" },
    { id: "chance_to_poison_support", name: "중독 확률 보조", type: "support", color: "dex" },
    { id: "charged_dash", name: "충전 질주", type: "skill", color: "dex" },
    { id: "charged_mines_support", name: "충전된 지뢰 보조", type: "support", color: "int" },
    { id: "charged_traps_support", name: "충전된 덫 보조", type: "support", color: "dex" },
    { id: "clarity", name: "명상", type: "skill", color: "int" },
    { id: "cleave", name: "회전베기", type: "skill", color: "str" },
    { id: "close_combat_support", name: "근접 전투 보조", type: "support", color: "dex" },
    { id: "cluster_traps_support", name: "무리 덫 보조", type: "support", color: "dex" },
    { id: "cobra_lash", name: "코브라 채찍", type: "skill", color: "dex" },
    { id: "cold_penetration_support", name: "냉기 관통 보조", type: "support", color: "dex" },
    { id: "cold_snap", name: "한파", type: "skill", color: "int" },
    { id: "cold_to_fire_support", name: "냉기 화염 전환 보조", type: "support", color: "str" },
    { id: "combustion_support", name: "연소 보조", type: "support", color: "int" },
    { id: "concentrated_effect_support", name: "효과 집중 보조", type: "support", color: "int" },
    { id: "conductivity", name: "전도성", type: "skill", color: "int" },
    { id: "consecrated_path", name: "축성의 진격", type: "skill", color: "str" },
    { id: "contagion", name: "전염", type: "skill", color: "int" },
    { id: "controlled_blaze_support", name: "제어된 불길 보조", type: "support", color: "str" },
    { id: "controlled_destruction_support", name: "제어된 파괴 보조", type: "support", color: "int" },
    { id: "conversion_trap", name: "전향 덫", type: "skill", color: "int" },
    { id: "corrupting_cry_support", name: "타락시키는 비명 보조", type: "support", color: "str" },
    { id: "corrupting_fever", name: "타락한 열병", type: "skill", color: "str" },
    { id: "crackling_lance", name: "치직대는 창", type: "skill", color: "int" },
    { id: "creeping_frost", name: "엄습하는 서리", type: "skill", color: "int" },
    { id: "cremation", name: "시체 소각", type: "skill", color: "dex" },
    { id: "critical_strike_affliction_support", name: "치명타 고통 격화 보조", type: "support", color: "dex" },
    { id: "cruelty_support", name: "잔혹 보조", type: "support", color: "str" },
    { id: "crushing_fist", name: "타쇄하는 주먹", type: "skill", color: "str" },
    { id: "culling_strike_support", name: "마무리 타격 보조", type: "support", color: "dex" },
    { id: "cyclone", name: "회오리바람", type: "skill", color: "dex" },
    { id: "damage_on_full_life_support", name: "최대 생명력 시 피해 보조", type: "support", color: "str" },
    { id: "dark_pact", name: "어둠의 서약", type: "skill", color: "int" },
    { id: "dash", name: "질주", type: "skill", color: "dex" },
    { id: "deadly_ailments_support", name: "치명적인 상태 이상 보조", type: "support", color: "dex" },
    { id: "decay_support", name: "부패 보조", type: "support", color: "int" },
    { id: "decoy_totem", name: "미끼 토템", type: "skill", color: "str" },
    { id: "defiance_banner", name: "저항의 깃발", type: "skill", color: "str" },
    { id: "desecrate", name: "모독", type: "skill", color: "dex" },
    { id: "despair", name: "절망", type: "skill", color: "int" },
    { id: "destructive_link", name: "파괴의 연결", type: "skill", color: "int" },
    { id: "determination", name: "결의", type: "skill", color: "str" },
    { id: "detonate_dead", name: "시체 폭발", type: "skill", color: "dex" },
    { id: "devour_support", name: "포식 보조", type: "support", color: "int" },
    { id: "devouring_totem", name: "포식 토템", type: "skill", color: "str" },
    { id: "discharge", name: "방출", type: "skill", color: "int" },
    { id: "discipline", name: "단련", type: "skill", color: "int" },
    { id: "divine_ire", name: "신성한 진노", type: "skill", color: "int" },
    { id: "divine_retribution", name: "신성한 응징", type: "skill", color: "int" },
    { id: "dominating_blow", name: "지배의 맹타", type: "skill", color: "str" },
    { id: "double_strike", name: "이중 타격", type: "skill", color: "dex" },
    { id: "dread_banner", name: "공포의 깃발", type: "skill", color: "str" },
    { id: "dual_strike", name: "쌍수 타격", type: "skill", color: "dex" },
    { id: "earthquake", name: "지진", type: "skill", color: "str" },
    { id: "earthshatter", name: "지면 분쇄", type: "skill", color: "str" },
    { id: "efficacy_support", name: "효력 보조", type: "support", color: "int" },
    { id: "elemental_damage_with_attacks_support", name: "공격 시 원소 피해 보조", type: "support", color: "str" },
    { id: "elemental_focus_support", name: "원소 집중 보조", type: "support", color: "int" },
    { id: "elemental_hit", name: "원소의 일격", type: "skill", color: "dex" },
    { id: "elemental_proliferation_support", name: "원소 확산 보조", type: "support", color: "int" },
    { id: "elemental_weakness", name: "원소 약화", type: "skill", color: "int" },
    { id: "endurance_charge_on_melee_stun_support", name: "기절 시 인내 충전 보조", type: "support", color: "str" },
    { id: "enduring_cry", name: "인내의 함성", type: "skill", color: "str" },
    { id: "energy_blade", name: "에너지 칼날", type: "skill", color: "int" },
    { id: "energy_leech_support", name: "에너지 흡수 보조", type: "support", color: "int" },
    { id: "enfeeble", name: "쇠약화", type: "skill", color: "int" },
    { id: "ensnaring_arrow", name: "올가미 화살", type: "skill", color: "dex" },
    { id: "essence_drain", name: "정수 흡수", type: "skill", color: "int" },
    { id: "eternal_blessing_support", name: "영원한 축복 보조", type: "support", color: "str" },
    { id: "ethereal_knives", name: "천상의 단도", type: "skill", color: "dex" },
    { id: "eviscerate", name: "내장 적출", type: "skill", color: "str" },
    { id: "expert_retaliation_support", name: "노련한 보복 보조", type: "support", color: "str" },
    { id: "explosive_arrow", name: "폭발 화살", type: "skill", color: "dex" },
    { id: "explosive_concoction", name: "폭발성 혼합물", type: "skill", color: "dex" },
    { id: "explosive_trap", name: "폭발 덫", type: "skill", color: "dex" },
    { id: "exsanguinate", name: "방혈", type: "skill", color: "str" },
    { id: "eye_of_winter", name: "겨울의 눈", type: "skill", color: "int" },
    { id: "faster_attacks_support", name: "공격 속도 증가 보조", type: "support", color: "dex" },
    { id: "faster_casting_support", name: "시전 속도 증가 보조", type: "support", color: "int" },
    { id: "faster_projectiles_support", name: "투사체 속도 증가 보조", type: "support", color: "dex" },
    { id: "feeding_frenzy_support", name: "격분 주입 보조", type: "support", color: "int" },
    { id: "fire_penetration_support", name: "화염 관통 보조", type: "support", color: "str" },
    { id: "fire_trap", name: "화염 덫", type: "skill", color: "dex" },
    { id: "fireball", name: "화염구", type: "skill", color: "int" },
    { id: "firestorm", name: "화염 폭풍", type: "skill", color: "int" },
    { id: "fist_of_war_support", name: "전쟁의 주먹 보조", type: "support", color: "str" },
    { id: "flame_dash", name: "화염 질주", type: "skill", color: "int" },
    { id: "flame_link", name: "화염의 연결", type: "skill", color: "str" },
    { id: "flame_surge", name: "화염 쇄도", type: "skill", color: "int" },
    { id: "flame_wall", name: "화염 벽", type: "skill", color: "int" },
    { id: "flameblast", name: "화염파", type: "skill", color: "int" },
    { id: "flamethrower_trap", name: "화염방사기 덫", type: "skill", color: "dex" },
    { id: "flamewood_support", name: "화염나무 보조", type: "support", color: "str" },
    { id: "flammability", name: "인화성", type: "skill", color: "int" },
    { id: "flesh_and_stone", name: "육체와 돌", type: "skill", color: "str" },
    { id: "flesh_offering", name: "살점 공물", type: "skill", color: "int" },
    { id: "flicker_strike", name: "점멸 타격", type: "skill", color: "dex" },
    { id: "focused_ballista_support", name: "쇠뇌 집중 사격 보조", type: "support", color: "dex" },
    { id: "focused_channelling_support", name: "집약된 집중 유지 보조", type: "support", color: "int" },
    { id: "forbidden_rite", name: "금단의 의식", type: "skill", color: "int" },
    { id: "fork_support", name: "갈래 보조", type: "support", color: "dex" },
    { id: "fortify_support", name: "방어 상승 보조", type: "support", color: "str" },
    { id: "freezing_pulse", name: "동결 파동", type: "skill", color: "int" },
    { id: "frenzy", name: "격분", type: "skill", color: "dex" },
    { id: "fresh_meat_support", name: "신선한 고기 보조", type: "support", color: "int" },
    { id: "frigid_bond_support", name: "차디찬 유대 보조", type: "support", color: "int" },
    { id: "frost_blades", name: "서리 칼날", type: "skill", color: "dex" },
    { id: "frost_bomb", name: "서리 폭탄", type: "skill", color: "int" },
    { id: "frost_shield", name: "서리 방패", type: "skill", color: "int" },
    { id: "frost_wall", name: "서리 방벽", type: "skill", color: "int" },
    { id: "frostbite", name: "동상", type: "skill", color: "int" },
    { id: "frostblink", name: "서리점멸", type: "skill", color: "int" },
    { id: "frostbolt", name: "서리 구체", type: "skill", color: "int" },
    { id: "frozen_legion", name: "얼어붙은 군단", type: "skill", color: "str" },
    { id: "galvanic_arrow", name: "충격 화살", type: "skill", color: "dex" },
    { id: "galvanic_field", name: "충격장", type: "skill", color: "int" },
    { id: "generals_cry", name: "장군의 함성", type: "skill", color: "str" },
    { id: "glacial_cascade", name: "빙하 폭포", type: "skill", color: "int" },
    { id: "glacial_hammer", name: "빙하 망치", type: "skill", color: "str" },
    { id: "glacial_shield_swipe", name: "빙하 방패 후려치기", type: "skill", color: "dex" },
    { id: "grace", name: "은총", type: "skill", color: "dex" },
    { id: "greater_multiple_projectiles_support", name: "상위 다중 투사체 보조", type: "support", color: "dex" },
    { id: "greater_volley_support", name: "상위 사격 공세 보조", type: "support", color: "dex" },
    { id: "ground_slam", name: "대지 강타", type: "skill", color: "str" },
    { id: "guardians_blessing_support", name: "수호자의 축복 보조", type: "support", color: "str" },
    { id: "haste", name: "가속", type: "skill", color: "dex" },
    { id: "hatred", name: "증오", type: "skill", color: "dex" },
    { id: "heavy_strike", name: "묵직한 타격", type: "skill", color: "str" },
    { id: "herald_of_agony", name: "고통의 전령", type: "skill", color: "dex" },
    { id: "herald_of_ash", name: "재의 전령", type: "skill", color: "str" },
    { id: "herald_of_ice", name: "얼음의 전령", type: "skill", color: "dex" },
    { id: "herald_of_purity", name: "순수의 전령", type: "skill", color: "str" },
    { id: "herald_of_thunder", name: "천둥의 전령", type: "skill", color: "int" },
    { id: "hex_bloom_support", name: "사술의 꽃 보조", type: "support", color: "int" },
    { id: "hexblast", name: "사술 폭발", type: "skill", color: "int" },
    { id: "hextouch_support", name: "사술 손길 보조", type: "support", color: "int" },
    { id: "high-impact_mine_support", name: "고충격 지뢰 보조", type: "support", color: "int" },
    { id: "holy_flame_totem", name: "신성한 화염 토템", type: "skill", color: "str" },
    { id: "hydrosphere", name: "물의 구체", type: "skill", color: "int" },
    { id: "hypothermia_support", name: "체온저하 보조", type: "support", color: "dex" },
    { id: "ice_bite_support", name: "얼음 쐐기 보조", type: "support", color: "dex" },
    { id: "ice_crash", name: "얼음 충격", type: "skill", color: "str" },
    { id: "ice_nova", name: "얼음 폭발", type: "skill", color: "int" },
    { id: "ice_shot", name: "얼음 화살", type: "skill", color: "dex" },
    { id: "ice_spear", name: "얼음 창", type: "skill", color: "int" },
    { id: "ice_trap", name: "얼음 덫", type: "skill", color: "dex" },
    { id: "icicle_mine", name: "고드름 지뢰", type: "skill", color: "int" },
    { id: "ignite_proliferation_support", name: "점화 확산 보조", type: "support", color: "int" },
    { id: "immolate_support", name: "번제 보조", type: "support", color: "int" },
    { id: "immortal_call", name: "불멸의 외침", type: "skill", color: "str" },
    { id: "impale_support", name: "꿰뚫기 보조", type: "support", color: "dex" },
    { id: "impending_doom_support", name: "임박한 멸망 보조", type: "support", color: "int" },
    { id: "incinerate", name: "소각", type: "skill", color: "int" },
    { id: "increased_area_of_effect_support", name: "효과 범위 증가 보조", type: "support", color: "int" },
    { id: "increased_critical_damage_support", name: "치명타 피해 증가 보조", type: "support", color: "int" },
    { id: "increased_critical_strikes_support", name: "치명타 증가 보조", type: "support", color: "int" },
    { id: "infernal_blow", name: "지옥불 맹타", type: "skill", color: "str" },
    { id: "infernal_cry", name: "지옥불 함성", type: "skill", color: "str" },
    { id: "infernal_legion_support", name: "지옥불 군단 보조", type: "support", color: "int" },
    { id: "infused_channelling_support", name: "깊어지는 집중 유지 보조", type: "support", color: "int" },
    { id: "innervate_support", name: "자극 보조", type: "support", color: "int" },
    { id: "intensify_support", name: "격화 보조", type: "support", color: "int" },
    { id: "intimidating_cry", name: "위협의 함성", type: "skill", color: "str" },
    { id: "intuitive_link", name: "직관의 연결", type: "skill", color: "dex" },
    { id: "iron_grip_support", name: "강철 손아귀 보조", type: "support", color: "str" },
    { id: "iron_will_support", name: "강철의 의지 보조", type: "support", color: "str" },
    { id: "kinetic_blast", name: "역학 폭발", type: "skill", color: "int" },
    { id: "kinetic_bolt", name: "역학 투사체", type: "skill", color: "int" },
    { id: "knockback_support", name: "밀어내기 보조", type: "support", color: "str" },
    { id: "lacerate", name: "피부 찢기", type: "skill", color: "dex" },
    { id: "lancing_steel", name: "강철 관통", type: "skill", color: "dex" },
    { id: "leap_slam", name: "도약 강타", type: "skill", color: "str" },
    { id: "lesser_multiple_projectiles_support", name: "하위 다중 투사체 보조", type: "support", color: "dex" },
    { id: "life_gain_on_hit_support", name: "명중 시 생명력 획득 보조", type: "support", color: "str" },
    { id: "life_leech_support", name: "생명력 흡수 보조", type: "support", color: "str" },
    { id: "lifetap_support", name: "생명력 전환 보조", type: "support", color: "str" },
    { id: "lightning_arrow", name: "번개 화살", type: "skill", color: "dex" },
    { id: "lightning_conduit", name: "번개 도관", type: "skill", color: "int" },
    { id: "lightning_penetration_support", name: "번개 관통 보조", type: "support", color: "int" },
    { id: "lightning_spire_trap", name: "번개 첨탑 덫", type: "skill", color: "int" },
    { id: "lightning_strike", name: "번개 타격", type: "skill", color: "dex" },
    { id: "lightning_tendrils", name: "덩굴 번개", type: "skill", color: "int" },
    { id: "lightning_trap", name: "번개 덫", type: "skill", color: "int" },
    { id: "lightning_warp", name: "번개 차원 이동", type: "skill", color: "int" },
    { id: "locus_mine_support", name: "궤적 지뢰 보조", type: "support", color: "dex" },
    { id: "maim_support", name: "힘줄 절단 보조", type: "support", color: "str" },
    { id: "malevolence", name: "악의", type: "skill", color: "int" },
    { id: "manabond", name: "마나 결속", type: "skill", color: "int" },
    { id: "manaforged_arrows_support", name: "마나벼림 화살 보조", type: "support", color: "dex" },
    { id: "mark_on_hit_support", name: "명중 시 징표 보조", type: "support", color: "dex" },
    { id: "meat_shield_support", name: "육탄 방어 보조", type: "support", color: "int" },
    { id: "melee_physical_damage_support", name: "근접 물리 피해 보조", type: "support", color: "str" },
    { id: "melee_splash_support", name: "근접 범위 피해 보조", type: "support", color: "str" },
    { id: "minefield_support", name: "지뢰밭 보조", type: "support", color: "int" },
    { id: "minion_damage_support", name: "소환수 피해 보조", type: "support", color: "int" },
    { id: "minion_life_support", name: "소환수 생명력 보조", type: "support", color: "int" },
    { id: "minion_speed_support", name: "소환수 속도 보조", type: "support", color: "int" },
    { id: "mirage_archer_support", name: "신기루 궁수 보조", type: "support", color: "dex" },
    { id: "molten_shell", name: "용암 방패", type: "skill", color: "str" },
    { id: "molten_strike", name: "용암 타격", type: "skill", color: "str" },
    { id: "momentum_support", name: "기세 보조", type: "support", color: "dex" },
    { id: "more_duration_support", name: "지속시간 증폭 보조", type: "support", color: "str" },
    { id: "multiple_totems_support", name: "다중 토템 보조", type: "support", color: "str" },
    { id: "multiple_traps_support", name: "다중 덫 보조", type: "support", color: "dex" },
    { id: "multistrike_support", name: "연속타격 보조", type: "support", color: "str" },
    { id: "nightblade_support", name: "밤의 칼날 보조", type: "support", color: "dex" },
    { id: "orb_of_storms", name: "폭풍 보주", type: "skill", color: "int" },
    { id: "overcharge_support", name: "과충전 보조", type: "support", color: "int" },
    { id: "overexertion_support", name: "전심전력 보조", type: "support", color: "str" },
    { id: "penance_brand", name: "속죄의 낙인", type: "skill", color: "int" },
    { id: "perforate", name: "천공", type: "skill", color: "str" },
    { id: "pestilent_strike", name: "전염성 일격", type: "skill", color: "dex" },
    { id: "petrified_blood", name: "피 석화", type: "skill", color: "str" },
    { id: "phase_run", name: "위이즈 런", type: "skill", color: "dex" },
    { id: "physical_to_lightning_support", name: "물리 번개 전환 보조", type: "support", color: "int" },
    { id: "pierce_support", name: "관통 보조", type: "support", color: "dex" },
    { id: "pinpoint_support", name: "핵심 조준 보조", type: "support", color: "int" },
    { id: "plague_bearer", name: "독성 운반자", type: "skill", color: "dex" },
    { id: "poachers_mark", name: "밀렴자의 징표", type: "skill", color: "dex" },
    { id: "point_blank_support", name: "근접 사격 보조", type: "support", color: "dex" },
    { id: "poisonous_concoction", name: "독성 혼합물", type: "skill", color: "dex" },
    { id: "power_charge_on_critical_support", name: "치명타 시 권능 충전 보조", type: "support", color: "int" },
    { id: "power_siphon", name: "권능 착취", type: "skill", color: "int" },
    { id: "precision", name: "정밀함", type: "skill", color: "dex" },
    { id: "predator_support", name: "포식자 보조", type: "support", color: "int" },
    { id: "pride", name: "자부심", type: "skill", color: "str" },
    { id: "prismatic_burst_support", name: "분광 격발 보조", type: "support", color: "int" },
    { id: "protective_link", name: "보호의 연결", type: "skill", color: "str" },
    { id: "pulverise_support", name: "분쇄 보조", type: "support", color: "str" },
    { id: "puncture", name: "관통상", type: "skill", color: "dex" },
    { id: "punishment", name: "응징", type: "skill", color: "str" },
    { id: "purifying_flame", name: "정화의 불길", type: "skill", color: "int" },
    { id: "purity_of_elements", name: "원소의 순수함", type: "skill", color: "int" },
    { id: "purity_of_fire", name: "불의 순수함", type: "skill", color: "str" },
    { id: "purity_of_ice", name: "얼음의 순수함", type: "skill", color: "dex" },
    { id: "purity_of_lightning", name: "번개의 순수함", type: "skill", color: "int" },
    { id: "pyroclast_mine", name: "화산탄 지뢰", type: "skill", color: "int" },
    { id: "rage_support", name: "격노 보조", type: "support", color: "str" },
    { id: "rage_vortex", name: "격노 소용돌이", type: "skill", color: "str" },
    { id: "rain_of_arrows", name: "화살비", type: "skill", color: "dex" },
    { id: "raise_spectre", name: "망령 소환", type: "skill", color: "int" },
    { id: "raise_zombie", name: "좀비 소환", type: "skill", color: "int" },
    { id: "rallying_cry", name: "집결의 함성", type: "skill", color: "str" },
    { id: "reap", name: "낫질", type: "skill", color: "str" },
    { id: "reave", name: "약탈", type: "skill", color: "dex" },
    { id: "rejuvenation_totem", name: "회복 토템", type: "skill", color: "str" },
    { id: "returning_projectiles_support", name: "돌아오는 투사체 보조", type: "support", color: "dex" },
    { id: "righteous_fire", name: "정의의 화염", type: "skill", color: "int" },
    { id: "rolling_magma", name: "몰려오는 마그마", type: "skill", color: "int" },
    { id: "rupture_support", name: "파열 보조", type: "support", color: "dex" },
    { id: "ruthless_support", name: "무자비 보조", type: "support", color: "str" },
    { id: "sacred_wisps_support", name: "신성한 도깨비불 보조", type: "support", color: "int" },
    { id: "sacrifice_support", name: "희생 보조", type: "support", color: "int" },
    { id: "sadism_support", name: "가학증 보조", type: "support", color: "dex" },
    { id: "scorching_ray", name: "작열 광선", type: "skill", color: "int" },
    { id: "scourge_arrow", name: "재앙의 화살", type: "skill", color: "dex" },
    { id: "searing_bond", name: "불타는 굴레", type: "skill", color: "str" },
    { id: "second_wind_support", name: "새로운 활력 보조", type: "support", color: "dex" },
    { id: "seismic_cry", name: "지진 함성", type: "skill", color: "str" },
    { id: "seismic_trap", name: "지진 덫", type: "skill", color: "dex" },
    { id: "shattering_steel", name: "강철 파편", type: "skill", color: "dex" },
    { id: "shield_charge", name: "방패 돌진", type: "skill", color: "str" },
    { id: "shield_crush", name: "방패 타쇄", type: "skill", color: "str" },
    { id: "shock_nova", name: "충격 폭발", type: "skill", color: "int" },
    { id: "shockwave_support", name: "충격파 보조", type: "support", color: "str" },
    { id: "shockwave_totem", name: "충격파 토템", type: "skill", color: "str" },
    { id: "shrapnel_ballista", name: "파편 쇠뇌", type: "skill", color: "dex" },
    { id: "siege_ballista", name: "공성 쇠뇌", type: "skill", color: "dex" },
    { id: "sigil_of_power", name: "힘의 부적", type: "skill", color: "int" },
    { id: "siphoning_trap", name: "착취 덫", type: "skill", color: "int" },
    { id: "smite", name: "징벌", type: "skill", color: "str" },
    { id: "smoke_mine", name: "연막 지뢰", type: "skill", color: "dex" },
    { id: "snipe", name: "저격", type: "skill", color: "dex" },
    { id: "snipers_mark", name: "저격수의 징표", type: "skill", color: "dex" },
    { id: "soul_link", name: "영혼의 연결", type: "skill", color: "int" },
    { id: "soulrend", name: "영혼 분리", type: "skill", color: "int" },
    { id: "spark", name: "전기불꽃", type: "skill", color: "int" },
    { id: "spectral_helix", name: "영체 나선", type: "skill", color: "dex" },
    { id: "spectral_shield_throw", name: "환영 방패 투척", type: "skill", color: "dex" },
    { id: "spectral_throw", name: "환영 무기 투척", type: "skill", color: "dex" },
    { id: "spell_cascade_support", name: "연속 주문 보조", type: "support", color: "int" },
    { id: "spell_echo_support", name: "주문 메아리 보조", type: "support", color: "int" },
    { id: "spell_totem_support", name: "주문 토템 보조", type: "support", color: "str" },
    { id: "spellblade_support", name: "주문칼날 보조", type: "support", color: "int" },
    { id: "spellslinger", name: "주문투척", type: "skill", color: "int" },
    { id: "spirit_offering", name: "영혼 공물", type: "skill", color: "int" },
    { id: "split_arrow", name: "분할 화살", type: "skill", color: "dex" },
    { id: "splitting_steel", name: "강철 분할", type: "skill", color: "dex" },
    { id: "static_strike", name: "정전기 타격", type: "skill", color: "str" },
    { id: "steelskin", name: "강철피부", type: "skill", color: "str" },
    { id: "storm_brand", name: "폭풍의 낙인", type: "skill", color: "int" },
    { id: "storm_burst", name: "폭풍 점사", type: "skill", color: "int" },
    { id: "storm_call", name: "폭풍 부름", type: "skill", color: "int" },
    { id: "storm_rain", name: "폭풍우", type: "skill", color: "dex" },
    { id: "stormbind", name: "폭풍 연대", type: "skill", color: "int" },
    { id: "stormblast_mine", name: "태풍 파열 지뢰", type: "skill", color: "int" },
    { id: "stun_support", name: "기절 보조", type: "support", color: "str" },
    { id: "summon_carrion_golem", name: "부패 골렘 소환", type: "skill", color: "int" },
    { id: "summon_chaos_golem", name: "카오스 골렘 소환", type: "skill", color: "int" },
    { id: "summon_flame_golem", name: "화염 골렘 소환", type: "skill", color: "str" },
    { id: "summon_holy_relic", name: "신성한 유물 소환", type: "skill", color: "int" },
    { id: "summon_ice_golem", name: "얼음 골렘 소환", type: "skill", color: "dex" },
    { id: "summon_lightning_golem", name: "번개 골렘 소환", type: "skill", color: "int" },
    { id: "summon_phantasm_support", name: "환영 소환 보조", type: "support", color: "int" },
    { id: "summon_raging_spirit", name: "격노의 유령 소환", type: "skill", color: "int" },
    { id: "summon_reaper", name: "수확자 소환", type: "skill", color: "int" },
    { id: "summon_skeletons", name: "해골 소환", type: "skill", color: "int" },
    { id: "summon_skitterbots", name: "원격 기폭 장치 소환", type: "skill", color: "int" },
    { id: "summon_stone_golem", name: "돌 골렘 소환", type: "skill", color: "str" },
    { id: "sunder", name: "산산조각", type: "skill", color: "str" },
    { id: "sweep", name: "휩쓸기", type: "skill", color: "str" },
    { id: "swift_affliction_support", name: "고통 격화 보조", type: "support", color: "dex" },
    { id: "swift_assembly_support", name: "재빠른 조립 보조", type: "support", color: "dex" },
    { id: "swiftbrand_support", name: "재빠른 낙인 보조", type: "support", color: "int" },
    { id: "swordstorm", name: "검의 폭풍", type: "skill", color: "str" },
    { id: "tectonic_slam", name: "지층 강타", type: "skill", color: "str" },
    { id: "tempest_shield", name: "폭풍의 방패", type: "skill", color: "int" },
    { id: "temporal_chains", name: "시간의 사슬", type: "skill", color: "dex" },
    { id: "temporal_rift", name: "시간의 균열", type: "skill", color: "dex" },
    { id: "tornado", name: "회오리", type: "skill", color: "dex" },
    { id: "tornado_shot", name: "회오리 사격", type: "skill", color: "dex" },
    { id: "toxic_rain", name: "맹독성 비", type: "skill", color: "dex" },
    { id: "trap_and_mine_damage_support", name: "덫 및 지뢰 피해 보조", type: "support", color: "dex" },
    { id: "trap_support", name: "덫 보조", type: "support", color: "dex" },
    { id: "trauma_support", name: "외상 보조", type: "support", color: "str" },
    { id: "trinity_support", name: "삼위일체 보조", type: "support", color: "int" },
    { id: "unbound_ailments_support", name: "벌어지는 상처 보조", type: "support", color: "int" },
    { id: "unearth", name: "발굴", type: "skill", color: "dex" },
    { id: "unleash_support", name: "촉발 보조", type: "support", color: "int" },
    { id: "urgent_orders_support", name: "긴급 명령 보조", type: "support", color: "str" },
    { id: "vampiric_link", name: "흡혈의 연결", type: "skill", color: "dex" },
    { id: "vengeful_cry", name: "복수의 함성", type: "skill", color: "str" },
    { id: "venom_gyre", name: "독액 선회", type: "skill", color: "dex" },
    { id: "vicious_projectiles_support", name: "포악한 투사체 보조", type: "support", color: "dex" },
    { id: "vigilant_strike", name: "경계 타격", type: "skill", color: "str" },
    { id: "vile_toxins_support", name: "끔찍한 독소 보조", type: "support", color: "dex" },
    { id: "viper_strike", name: "맹독 타격", type: "skill", color: "dex" },
    { id: "vitality", name: "활력", type: "skill", color: "str" },
    { id: "void_manipulation_support", name: "공허 조작 보조", type: "support", color: "dex" },
    { id: "void_sphere", name: "공허 구체", type: "skill", color: "int" },
    { id: "volatility_support", name: "일촉즉발 보조", type: "support", color: "str" },
    { id: "volley_support", name: "사격 공세 보조", type: "support", color: "dex" },
    { id: "withering_touch_support", name: "위축의 손길 보조", type: "support", color: "dex" },
  ],
  questRewards: [
    { act: 1, questName: "사이렌의 마침곡", rewards: [
      { gemId: "absolution", classes: ["templar"] },
      { gemId: "arc", classes: ["witch"] },
      { gemId: "blade_vortex", classes: ["shadow", "scion"] },
      { gemId: "blazing_salvo", classes: ["witch", "templar"] },
      { gemId: "chain_hook", classes: ["marauder"] },
      { gemId: "creeping_frost", classes: ["witch"] },
      { gemId: "earthshatter", classes: ["marauder", "duelist"] },
      { gemId: "elemental_hit", classes: ["ranger"] },
      { gemId: "essence_drain", classes: ["witch", "shadow"] },
      { gemId: "exsanguinate", classes: ["scion"] },
      { gemId: "fire_trap", classes: ["shadow"] },
      { gemId: "flesh_offering", classes: ["witch"] },
      { gemId: "ice_nova", classes: ["witch", "templar", "scion"] },
      { gemId: "icicle_mine", classes: ["shadow"] },
      { gemId: "infernal_blow", classes: ["marauder"] },
      { gemId: "lacerate", classes: ["duelist"] },
      { gemId: "lightning_arrow", classes: ["ranger"] },
      { gemId: "lightning_strike", classes: ["ranger"] },
      { gemId: "lightning_trap", classes: ["shadow"] },
      { gemId: "manabond", classes: ["templar", "witch"] },
      { gemId: "poisonous_concoction", classes: ["ranger"] },
      { gemId: "rain_of_arrows", classes: ["duelist", "ranger", "scion"] },
      { gemId: "reave", classes: ["ranger", "shadow"] },
      { gemId: "scorching_ray", classes: ["witch", "templar", "scion"] },
      { gemId: "searing_bond", classes: ["templar"] },
      { gemId: "shattering_steel", classes: ["duelist"] },
      { gemId: "siege_ballista", classes: ["ranger"] },
      { gemId: "spectral_helix", classes: ["scion"] },
      { gemId: "static_strike", classes: ["templar", "marauder", "scion"] },
      { gemId: "storm_brand", classes: ["templar"] },
      { gemId: "storm_burst", classes: ["templar", "scion"] },
      { gemId: "storm_call", classes: ["templar"] },
      { gemId: "sunder", classes: ["marauder"] },
      { gemId: "sweep", classes: ["marauder", "duelist"] },
      { gemId: "toxic_rain", classes: ["ranger"] },
    ]},
    { act: 1, questName: "로아 알 깔트리기", rewards: [
      { gemId: "bear_trap", classes: ["ranger", "shadow", "scion"] },
      { gemId: "blood_and_sand", classes: ["duelist"] },
      { gemId: "contagion", classes: ["witch", "shadow"] },
      { gemId: "crushing_fist", classes: ["marauder", "duelist"] },
      { gemId: "dash", classes: ["duelist", "ranger", "shadow", "scion"] },
      { gemId: "decoy_totem", classes: ["marauder", "duelist", "scion"] },
      { gemId: "detonate_dead", classes: ["witch", "shadow"] },
      { gemId: "flame_wall", classes: ["witch", "templar"] },
      { gemId: "frost_bomb", classes: ["witch", "templar", "scion"] },
      { gemId: "frostblink", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "holy_flame_totem", classes: ["templar"] },
      { gemId: "orb_of_storms", classes: ["witch", "shadow"] },
      { gemId: "puncture", classes: ["duelist", "ranger"] },
      { gemId: "shield_charge", classes: ["marauder", "duelist", "templar", "scion"] },
      { gemId: "shrapnel_ballista", classes: ["ranger"] },
      { gemId: "snipers_mark", classes: ["ranger", "duelist"] },
      { gemId: "steelskin", classes: ["marauder"] },
      { gemId: "summon_holy_relic", classes: ["templar"] },
      { gemId: "summon_raging_spirit", classes: ["witch"] },
    ]},
    { act: 1, questName: "눈 앞의 적", rewards: [
      { gemId: "blight", classes: ["witch", "shadow"] },
      { gemId: "caustic_arrow", classes: ["ranger"] },
      { gemId: "cleave", classes: ["duelist"] },
      { gemId: "cobra_lash", classes: ["shadow"] },
      { gemId: "ethereal_knives", classes: ["shadow"] },
      { gemId: "explosive_trap", classes: ["shadow"] },
      { gemId: "freezing_pulse", classes: ["witch", "shadow"] },
      { gemId: "frost_blades", classes: ["ranger"] },
      { gemId: "frostbolt", classes: ["templar"] },
      { gemId: "galvanic_arrow", classes: ["duelist", "ranger"] },
      { gemId: "ground_slam", classes: ["marauder"] },
      { gemId: "ice_shot", classes: ["ranger"] },
      { gemId: "kinetic_bolt", classes: ["witch"] },
      { gemId: "lightning_tendrils", classes: ["witch", "templar", "scion"] },
      { gemId: "molten_strike", classes: ["templar", "marauder", "duelist", "scion"] },
      { gemId: "perforate", classes: ["duelist"] },
      { gemId: "purifying_flame", classes: ["templar"] },
      { gemId: "raise_zombie", classes: ["witch"] },
      { gemId: "rolling_magma", classes: ["witch", "templar"] },
      { gemId: "shield_crush", classes: ["marauder"] },
      { gemId: "smite", classes: ["templar"] },
      { gemId: "split_arrow", classes: ["ranger", "scion"] },
      { gemId: "splitting_steel", classes: ["duelist", "scion"] },
      { gemId: "stormblast_mine", classes: ["shadow"] },
    ]},
    { act: 1, questName: "감금된 덱치", rewards: [
      { gemId: "blink_arrow", classes: ["duelist", "ranger", "scion"] },
      { gemId: "bodyswap", classes: ["witch"] },
      { gemId: "clarity", classes: ["witch", "templar", "shadow"] },
      { gemId: "enduring_cry", classes: ["marauder", "duelist"] },
      { gemId: "flame_dash", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "intimidating_cry", classes: ["marauder", "duelist"] },
      { gemId: "leap_slam", classes: ["templar", "marauder", "duelist", "scion"] },
      { gemId: "lightning_warp", classes: ["witch"] },
      { gemId: "precision", classes: ["duelist", "ranger", "shadow"] },
      { gemId: "siphoning_trap", classes: ["shadow"] },
      { gemId: "smoke_mine", classes: ["ranger", "shadow"] },
      { gemId: "summon_skeletons", classes: ["witch"] },
      { gemId: "unearth", classes: ["shadow"] },
      { gemId: "added_cold_damage_support", classes: ["ranger", "shadow", "scion"] },
      { gemId: "added_fire_damage_support", classes: ["templar", "marauder", "duelist", "scion"] },
      { gemId: "added_lightning_damage_support", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "arrow_nova_support", classes: ["ranger"] },
      { gemId: "combustion_support", classes: ["witch", "templar"] },
      { gemId: "devour_support", classes: ["witch"] },
      { gemId: "efficacy_support", classes: ["witch"] },
      { gemId: "faster_attacks_support", classes: ["marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "flamewood_support", classes: ["marauder"] },
      { gemId: "infernal_legion_support", classes: ["witch"] },
      { gemId: "lesser_multiple_projectiles_support", classes: ["duelist", "ranger", "shadow", "scion"] },
      { gemId: "lifetap_support", classes: ["marauder", "templar", "duelist", "scion"] },
      { gemId: "maim_support", classes: ["duelist"] },
      { gemId: "manaforged_arrows_support", classes: ["ranger"] },
      { gemId: "melee_splash_support", classes: ["templar", "marauder", "duelist", "ranger", "scion"] },
      { gemId: "minion_damage_support", classes: ["witch"] },
      { gemId: "multiple_traps_support", classes: ["shadow"] },
      { gemId: "unbound_ailments_support", classes: ["witch", "scion"] },
      { gemId: "void_manipulation_support", classes: ["witch", "ranger", "shadow"] },
    ]},
    { act: 1, questName: "자비로운 임무", rewards: [
      { gemId: "ancestral_call_support", classes: ["templar", "marauder", "duelist", "scion"] },
      { gemId: "arcane_surge_support", classes: ["templar", "scion"] },
      { gemId: "chance_to_bleed_support", classes: ["templar", "marauder", "scion"] },
      { gemId: "chance_to_poison_support", classes: ["witch", "duelist", "ranger", "scion"] },
      { gemId: "elemental_proliferation_support", classes: ["witch", "shadow", "scion"] },
      { gemId: "infused_channelling_support", classes: ["witch", "templar", "shadow"] },
      { gemId: "mirage_archer_support", classes: ["duelist", "ranger"] },
      { gemId: "momentum_support", classes: ["marauder", "duelist", "shadow"] },
      { gemId: "pierce_support", classes: ["duelist", "shadow", "scion", "ranger"] },
      { gemId: "ruthless_support", classes: ["templar", "duelist", "scion"] },
      { gemId: "spell_cascade_support", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "summon_phantasm_support", classes: ["witch", "scion"] },
      { gemId: "swift_assembly_support", classes: ["shadow"] },
      { gemId: "volley_support", classes: ["duelist", "ranger", "shadow", "scion"] },
    ]},
    { act: 2, questName: "검은 침락자", rewards: [
      { gemId: "ancestral_cry", classes: ["marauder", "duelist"] },
      { gemId: "arcane_cloak", classes: ["witch", "templar", "shadow"] },
      { gemId: "arctic_armour", classes: ["witch", "ranger", "shadow", "scion"] },
      { gemId: "assassins_mark", classes: ["shadow"] },
      { gemId: "blade_blast", classes: ["shadow"] },
      { gemId: "blood_rage", classes: ["duelist", "ranger", "shadow"] },
      { gemId: "brand_recall", classes: ["templar"] },
      { gemId: "cold_snap", classes: ["witch", "shadow"] },
      { gemId: "corrupting_fever", classes: ["marauder", "duelist", "scion"] },
      { gemId: "defiance_banner", classes: ["duelist"] },
      { gemId: "desecrate", classes: ["witch"] },
      { gemId: "divine_retribution", classes: ["templar"] },
      { gemId: "ensnaring_arrow", classes: ["ranger"] },
      { gemId: "eviscerate", classes: ["marauder", "duelist"] },
      { gemId: "flesh_and_stone", classes: ["duelist"] },
      { gemId: "frenzy", classes: ["duelist", "ranger", "scion"] },
      { gemId: "galvanic_field", classes: ["witch"] },
      { gemId: "glacial_shield_swipe", classes: ["duelist"] },
      { gemId: "herald_of_agony", classes: ["ranger", "shadow"] },
      { gemId: "herald_of_ash", classes: [] },
      { gemId: "herald_of_ice", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "herald_of_purity", classes: ["templar"] },
      { gemId: "herald_of_thunder", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "molten_shell", classes: ["marauder"] },
      { gemId: "poachers_mark", classes: ["ranger", "duelist"] },
      { gemId: "poachers_mark", classes: ["ranger", "duelist"] },
      { gemId: "seismic_cry", classes: ["marauder", "duelist"] },
      { gemId: "summon_skitterbots", classes: ["shadow"] },
      { gemId: "swordstorm", classes: ["duelist"] },
    ]},
    { act: 2, questName: "날카로운 눈 넓은 시야", rewards: [
      { gemId: "close_combat_support", classes: ["marauder", "duelist", "ranger"] },
      { gemId: "concentrated_effect_support", classes: ["witch", "templar", "scion"] },
      { gemId: "controlled_destruction_support", classes: ["witch", "templar"] },
      { gemId: "cruelty_support", classes: ["marauder", "templar", "witch", "scion"] },
      { gemId: "deadly_ailments_support", classes: ["shadow", "scion"] },
      { gemId: "elemental_damage_with_attacks_support", classes: ["templar", "marauder", "duelist", "ranger", "scion"] },
      { gemId: "elemental_focus_support", classes: ["witch", "templar", "shadow"] },
      { gemId: "faster_casting_support", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "fresh_meat_support", classes: ["witch"] },
      { gemId: "melee_physical_damage_support", classes: ["templar", "marauder", "duelist", "shadow", "scion"] },
      { gemId: "minion_speed_support", classes: ["witch"] },
      { gemId: "nightblade_support", classes: ["shadow"] },
      { gemId: "overcharge_support", classes: ["witch"] },
      { gemId: "predator_support", classes: ["witch"] },
      { gemId: "rage_support", classes: ["marauder", "duelist"] },
      { gemId: "sacred_wisps_support", classes: ["witch"] },
      { gemId: "sadism_support", classes: ["duelist", "scion"] },
      { gemId: "shockwave_support", classes: ["templar", "marauder"] },
      { gemId: "trap_and_mine_damage_support", classes: ["shadow"] },
      { gemId: "trinity_support", classes: ["witch", "shadow", "duelist", "ranger"] },
      { gemId: "vicious_projectiles_support", classes: ["duelist", "ranger", "scion"] },
      { gemId: "volatility_support", classes: ["marauder"] },
    ]},
    { act: 3, questName: "떠나보낸 연인", rewards: [
      { gemId: "alchemists_mark", classes: ["ranger"] },
      { gemId: "anger", classes: ["marauder", "scion"] },
      { gemId: "bane", classes: ["witch", "shadow", "scion"] },
      { gemId: "battlemages_cry", classes: ["templar"] },
      { gemId: "conductivity", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "despair", classes: ["witch", "ranger", "shadow"] },
      { gemId: "determination", classes: ["marauder"] },
      { gemId: "discipline", classes: ["witch"] },
      { gemId: "dread_banner", classes: ["duelist"] },
      { gemId: "elemental_weakness", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "enfeeble", classes: ["shadow", "templar", "witch"] },
      { gemId: "flammability", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "frostbite", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "generals_cry", classes: ["marauder"] },
      { gemId: "grace", classes: ["duelist", "ranger"] },
      { gemId: "hatred", classes: ["duelist", "ranger", "shadow", "scion"] },
      { gemId: "infernal_cry", classes: ["marauder"] },
      { gemId: "malevolence", classes: ["witch", "shadow", "scion"] },
      { gemId: "petrified_blood", classes: ["marauder", "duelist", "scion"] },
      { gemId: "plague_bearer", classes: ["shadow"] },
      { gemId: "pride", classes: ["marauder", "duelist"] },
      { gemId: "punishment", classes: ["marauder", "scion", "templar"] },
      { gemId: "purity_of_elements", classes: ["witch"] },
      { gemId: "rallying_cry", classes: ["duelist"] },
      { gemId: "spellslinger", classes: ["witch"] },
      { gemId: "temporal_chains", classes: ["witch", "scion", "shadow"] },
    ]},
    { act: 3, questName: "오른손 절단", rewards: [
      { gemId: "armageddon_brand", classes: ["templar"] },
      { gemId: "artillery_ballista", classes: ["ranger"] },
      { gemId: "ball_lightning", classes: ["witch", "shadow"] },
      { gemId: "blade_flurry", classes: ["ranger", "shadow", "scion"] },
      { gemId: "bladefall", classes: ["shadow", "scion"] },
      { gemId: "bladestorm", classes: ["duelist"] },
      { gemId: "blast_rain", classes: ["duelist", "ranger"] },
      { gemId: "charged_dash", classes: ["duelist", "ranger", "shadow", "scion"] },
      { gemId: "consecrated_path", classes: ["templar"] },
      { gemId: "crackling_lance", classes: ["witch"] },
      { gemId: "cremation", classes: ["witch", "shadow"] },
      { gemId: "cyclone", classes: ["marauder", "duelist", "scion"] },
      { gemId: "divine_ire", classes: ["templar", "scion"] },
      { gemId: "dominating_blow", classes: ["templar"] },
      { gemId: "earthquake", classes: ["marauder"] },
      { gemId: "explosive_concoction", classes: ["ranger"] },
      { gemId: "eye_of_winter", classes: ["witch"] },
      { gemId: "firestorm", classes: ["witch", "templar"] },
      { gemId: "flameblast", classes: ["witch", "templar", "scion"] },
      { gemId: "flamethrower_trap", classes: ["shadow"] },
      { gemId: "glacial_cascade", classes: ["witch"] },
      { gemId: "hexblast", classes: ["shadow", "witch", "scion"] },
      { gemId: "ice_crash", classes: ["templar", "marauder", "duelist"] },
      { gemId: "kinetic_blast", classes: ["witch"] },
      { gemId: "lancing_steel", classes: ["duelist"] },
      { gemId: "lightning_conduit", classes: ["witch"] },
      { gemId: "lightning_spire_trap", classes: ["shadow"] },
      { gemId: "penance_brand", classes: ["templar"] },
      { gemId: "pestilent_strike", classes: ["shadow"] },
      { gemId: "pyroclast_mine", classes: ["shadow"] },
      { gemId: "rage_vortex", classes: ["marauder"] },
      { gemId: "raise_spectre", classes: ["witch"] },
      { gemId: "reap", classes: ["scion"] },
      { gemId: "scourge_arrow", classes: ["ranger"] },
      { gemId: "seismic_trap", classes: ["shadow"] },
      { gemId: "shock_nova", classes: ["templar"] },
      { gemId: "shockwave_totem", classes: ["templar"] },
      { gemId: "soulrend", classes: ["witch", "shadow", "scion"] },
      { gemId: "spectral_shield_throw", classes: ["duelist"] },
      { gemId: "storm_rain", classes: ["ranger"] },
      { gemId: "stormbind", classes: ["witch", "templar"] },
      { gemId: "summon_reaper", classes: ["witch"] },
      { gemId: "tectonic_slam", classes: ["marauder", "scion"] },
      { gemId: "tornado_shot", classes: ["ranger", "scion"] },
    ]},
    { act: 3, questName: "운명의 시련", rewards: [
      { gemId: "archmage_support", classes: ["witch", "templar", "shadow"] },
      { gemId: "arrogance_support", classes: ["marauder", "templar", "duelist", "scion"] },
      { gemId: "blasphemy_support", classes: ["witch", "templar"] },
      { gemId: "bloodthirst_support", classes: ["marauder", "duelist", "scion"] },
      { gemId: "burning_damage_support", classes: ["witch", "templar"] },
      { gemId: "charged_mines_support", classes: ["shadow"] },
      { gemId: "charged_traps_support", classes: ["shadow"] },
      { gemId: "cold_penetration_support", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "controlled_blaze_support", classes: ["marauder"] },
      { gemId: "corrupting_cry_support", classes: ["marauder"] },
      { gemId: "critical_strike_affliction_support", classes: ["ranger", "shadow"] },
      { gemId: "energy_leech_support", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "expert_retaliation_support", classes: ["duelist"] },
      { gemId: "faster_projectiles_support", classes: ["shadow"] },
      { gemId: "feeding_frenzy_support", classes: ["witch"] },
      { gemId: "fire_penetration_support", classes: ["witch", "templar", "scion"] },
      { gemId: "focused_ballista_support", classes: ["ranger"] },
      { gemId: "focused_channelling_support", classes: ["witch", "shadow"] },
      { gemId: "fork_support", classes: ["ranger"] },
      { gemId: "fortify_support", classes: ["templar", "marauder", "duelist", "ranger", "scion"] },
      { gemId: "guardians_blessing_support", classes: ["templar"] },
      { gemId: "high-impact_mine_support", classes: ["shadow"] },
      { gemId: "hypothermia_support", classes: ["duelist", "ranger"] },
      { gemId: "ice_bite_support", classes: ["ranger", "shadow", "scion"] },
      { gemId: "impale_support", classes: ["marauder", "duelist", "ranger"] },
      { gemId: "impending_doom_support", classes: ["shadow", "witch", "scion"] },
      { gemId: "innervate_support", classes: ["shadow", "scion"] },
      { gemId: "intensify_support", classes: ["witch", "templar", "scion"] },
      { gemId: "life_leech_support", classes: ["marauder", "duelist", "ranger", "scion"] },
      { gemId: "lightning_penetration_support", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "meat_shield_support", classes: ["witch"] },
      { gemId: "more_duration_support", classes: ["marauder"] },
      { gemId: "pinpoint_support", classes: ["shadow", "witch"] },
      { gemId: "pulverise_support", classes: ["templar", "marauder", "duelist"] },
      { gemId: "sacrifice_support", classes: ["witch"] },
      { gemId: "second_wind_support", classes: ["ranger", "shadow"] },
      { gemId: "swift_affliction_support", classes: ["witch", "shadow"] },
      { gemId: "swiftbrand_support", classes: ["templar"] },
      { gemId: "urgent_orders_support", classes: ["marauder", "duelist"] },
    ]},
    { act: 4, questName: "봉인 해제", rewards: [
      { gemId: "ambush", classes: ["shadow"] },
      { gemId: "berserk", classes: ["marauder"] },
      { gemId: "flame_link", classes: ["scion"] },
      { gemId: "frost_shield", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "frozen_legion", classes: ["templar"] },
      { gemId: "hydrosphere", classes: ["witch", "templar"] },
      { gemId: "intuitive_link", classes: ["scion"] },
      { gemId: "sigil_of_power", classes: ["witch", "templar"] },
      { gemId: "snipe", classes: ["ranger"] },
      { gemId: "soul_link", classes: ["scion"] },
      { gemId: "summon_carrion_golem", classes: ["witch", "templar"] },
      { gemId: "summon_chaos_golem", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "summon_flame_golem", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "summon_ice_golem", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "summon_lightning_golem", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "summon_stone_golem", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "temporal_rift", classes: ["shadow"] },
      { gemId: "tornado", classes: ["ranger", "shadow"] },
    ]},
    { act: 4, questName: "영원한 악몽", rewards: [
      { gemId: "arcanist_brand", classes: ["templar"] },
      { gemId: "barrage_support", classes: ["duelist", "ranger", "shadow", "scion"] },
      { gemId: "behead_support", classes: ["marauder", "duelist"] },
      { gemId: "bonechill_support", classes: ["witch", "shadow"] },
      { gemId: "brutality_support", classes: ["marauder"] },
      { gemId: "chain_support", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "cluster_traps_support", classes: ["shadow"] },
      { gemId: "decay_support", classes: ["witch", "scion"] },
      { gemId: "eternal_blessing_support", classes: ["marauder"] },
      { gemId: "fist_of_war_support", classes: ["templar", "marauder", "duelist"] },
      { gemId: "frigid_bond_support", classes: ["templar", "scion"] },
      { gemId: "greater_multiple_projectiles_support", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "greater_volley_support", classes: ["duelist", "ranger", "shadow", "scion"] },
      { gemId: "hex_bloom_support", classes: ["witch"] },
      { gemId: "ignite_proliferation_support", classes: ["templar"] },
      { gemId: "immolate_support", classes: ["witch", "scion"] },
      { gemId: "increased_area_of_effect_support", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "minefield_support", classes: ["shadow"] },
      { gemId: "multiple_totems_support", classes: ["templar", "marauder"] },
      { gemId: "multistrike_support", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "overexertion_support", classes: ["marauder"] },
      { gemId: "returning_projectiles_support", classes: ["ranger", "shadow", "scion"] },
      { gemId: "rupture_support", classes: ["ranger"] },
      { gemId: "spell_echo_support", classes: ["witch", "templar", "marauder", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "spellblade_support", classes: ["templar"] },
      { gemId: "trauma_support", classes: ["marauder", "duelist"] },
      { gemId: "unleash_support", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "vile_toxins_support", classes: ["shadow"] },
      { gemId: "withering_touch_support", classes: ["ranger", "shadow"] },
    ]},
  ],
  vendorRewards: [
    { act: 1, questName: "사이렌의 마침곡", npc: "네사", rewards: [
      { gemId: "absolution", classes: ["marauder", "witch", "templar", "scion"] },
      { gemId: "arc", classes: ["shadow", "templar", "witch"] },
      { gemId: "barrage", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "blade_trap", classes: ["ranger", "shadow", "scion"] },
      { gemId: "blade_vortex", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "blazing_salvo", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "bone_offering", classes: ["scion", "templar", "witch"] },
      { gemId: "chain_hook", classes: ["duelist", "marauder", "scion"] },
      { gemId: "creeping_frost", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "earthshatter", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "elemental_hit", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "essence_drain", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "exsanguinate", classes: ["marauder", "scion", "shadow", "templar", "witch"] },
      { gemId: "fire_trap", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "flame_surge", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "flesh_offering", classes: ["scion", "templar", "witch"] },
      { gemId: "ice_nova", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "ice_spear", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "icicle_mine", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "incinerate", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "infernal_blow", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "lacerate", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "lightning_arrow", classes: ["duelist", "ranger", "shadow"] },
      { gemId: "lightning_strike", classes: ["duelist", "ranger", "scion", "shadow", "templar"] },
      { gemId: "lightning_trap", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "manabond", classes: ["templar", "witch", "shadow", "scion"] },
      { gemId: "poisonous_concoction", classes: ["duelist", "shadow", "scion", "ranger"] },
      { gemId: "power_siphon", classes: ["scion", "shadow", "witch"] },
      { gemId: "rain_of_arrows", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "reave", classes: ["duelist", "ranger", "shadow"] },
      { gemId: "scorching_ray", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "searing_bond", classes: ["marauder", "templar", "witch"] },
      { gemId: "shattering_steel", classes: ["duelist", "ranger", "scion"] },
      { gemId: "siege_ballista", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "spectral_helix", classes: ["marauder", "templar", "duelist", "ranger", "shadow", "scion"] },
      { gemId: "spirit_offering", classes: ["scion", "templar", "witch"] },
      { gemId: "static_strike", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "storm_brand", classes: ["scion", "templar", "witch"] },
      { gemId: "storm_burst", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "storm_call", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "sunder", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "sweep", classes: ["duelist", "marauder", "templar"] },
      { gemId: "toxic_rain", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "venom_gyre", classes: ["ranger", "scion", "shadow"] },
    ]},
    { act: 1, questName: "로아 알 깔트리기", npc: "네사", rewards: [
      { gemId: "animate_weapon", classes: ["scion", "shadow", "witch"] },
      { gemId: "bear_trap", classes: ["marauder", "ranger", "scion", "shadow"] },
      { gemId: "blood_and_sand", classes: ["duelist", "marauder", "ranger", "scion"] },
      { gemId: "contagion", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "conversion_trap", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "crushing_fist", classes: ["marauder", "duelist", "templar", "scion"] },
      { gemId: "dash", classes: [] },
      { gemId: "decoy_totem", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "detonate_dead", classes: ["ranger", "shadow", "witch"] },
      { gemId: "devouring_totem", classes: ["duelist", "marauder", "ranger", "scion", "templar", "witch"] },
      { gemId: "flame_wall", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "frost_bomb", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "frost_wall", classes: ["duelist", "templar", "witch"] },
      { gemId: "frostblink", classes: [] },
      { gemId: "holy_flame_totem", classes: ["marauder", "templar", "witch"] },
      { gemId: "orb_of_storms", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "puncture", classes: ["duelist", "ranger", "shadow"] },
      { gemId: "rejuvenation_totem", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "shield_charge", classes: [] },
      { gemId: "shrapnel_ballista", classes: ["duelist", "marauder", "ranger", "scion", "shadow"] },
      { gemId: "snipers_mark", classes: ["duelist", "ranger", "shadow", "scion"] },
      { gemId: "steelskin", classes: ["templar", "marauder", "duelist", "scion"] },
      { gemId: "summon_holy_relic", classes: ["templar", "witch"] },
      { gemId: "summon_raging_spirit", classes: ["scion", "templar", "witch"] },
      { gemId: "vigilant_strike", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
    ]},
    { act: 1, questName: "눈 앞의 적", npc: "네사", rewards: [
      { gemId: "blight", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "burning_arrow", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "caustic_arrow", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "cleave", classes: ["duelist", "marauder", "ranger", "scion"] },
      { gemId: "cobra_lash", classes: ["ranger", "scion", "shadow"] },
      { gemId: "double_strike", classes: ["duelist", "marauder", "ranger", "scion", "shadow"] },
      { gemId: "dual_strike", classes: ["duelist", "marauder", "ranger", "scion", "shadow"] },
      { gemId: "ethereal_knives", classes: ["marauder", "shadow", "witch"] },
      { gemId: "explosive_trap", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "fireball", classes: ["marauder", "scion", "shadow", "templar", "witch"] },
      { gemId: "freezing_pulse", classes: ["shadow", "templar", "witch"] },
      { gemId: "frost_blades", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "frostbolt", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "galvanic_arrow", classes: ["duelist", "ranger", "scion"] },
      { gemId: "glacial_hammer", classes: ["duelist", "marauder", "templar"] },
      { gemId: "ground_slam", classes: ["duelist", "marauder", "templar"] },
      { gemId: "heavy_strike", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "ice_shot", classes: ["duelist", "ranger", "scion"] },
      { gemId: "kinetic_bolt", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "lightning_tendrils", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "molten_strike", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "perforate", classes: ["duelist", "marauder", "ranger", "scion"] },
      { gemId: "purifying_flame", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "raise_zombie", classes: ["scion", "templar", "witch"] },
      { gemId: "rolling_magma", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "shield_crush", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "smite", classes: ["marauder", "scion", "templar"] },
      { gemId: "spark", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "spectral_throw", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "split_arrow", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "splitting_steel", classes: ["duelist", "scion", "ranger"] },
      { gemId: "stormblast_mine", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "viper_strike", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "arcane_surge_support", classes: ["witch"] },
      { gemId: "chance_to_bleed_support", classes: ["duelist"] },
      { gemId: "chance_to_poison_support", classes: ["shadow"] },
      { gemId: "elemental_proliferation_support", classes: ["templar"] },
      { gemId: "momentum_support", classes: ["scion", "ranger"] },
      { gemId: "prismatic_burst_support", classes: ["templar", "shadow", "witch", "scion"] },
      { gemId: "ruthless_support", classes: ["marauder"] },
    ]},
    { act: 1, questName: "감금된 덱치", npc: "네사", rewards: [
      { gemId: "blink_arrow", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "bodyswap", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "clarity", classes: [] },
      { gemId: "enduring_cry", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "flame_dash", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "flicker_strike", classes: ["duelist", "marauder", "ranger", "scion", "shadow"] },
      { gemId: "intimidating_cry", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "leap_slam", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "lightning_warp", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "precision", classes: [] },
      { gemId: "siphoning_trap", classes: ["scion", "shadow", "witch"] },
      { gemId: "smoke_mine", classes: ["duelist", "marauder", "ranger", "shadow", "witch"] },
      { gemId: "summon_skeletons", classes: ["scion", "templar", "witch"] },
      { gemId: "unearth", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "vitality", classes: [] },
      { gemId: "added_cold_damage_support", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "added_fire_damage_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "added_lightning_damage_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "additional_accuracy_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "arrow_nova_support", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "ballista_totem_support", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "blastchain_mine_support", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "blind_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow"] },
      { gemId: "chance_to_flee_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow"] },
      { gemId: "combustion_support", classes: ["marauder", "shadow", "templar", "witch"] },
      { gemId: "devour_support", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "efficacy_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "faster_attacks_support", classes: ["duelist", "marauder", "ranger", "shadow", "scion"] },
      { gemId: "flamewood_support", classes: ["marauder", "templar", "scion"] },
      { gemId: "increased_critical_strikes_support", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "infernal_legion_support", classes: ["templar", "witch"] },
      { gemId: "knockback_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "lesser_multiple_projectiles_support", classes: ["duelist", "ranger", "scion", "shadow", "witch"] },
      { gemId: "life_gain_on_hit_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "lifetap_support", classes: ["marauder", "templar", "duelist", "scion"] },
      { gemId: "locus_mine_support", classes: ["ranger", "witch", "shadow", "scion"] },
      { gemId: "maim_support", classes: ["duelist", "marauder", "ranger", "scion"] },
      { gemId: "manaforged_arrows_support", classes: ["ranger", "scion", "shadow"] },
      { gemId: "melee_splash_support", classes: [] },
      { gemId: "minion_damage_support", classes: ["scion", "templar", "witch"] },
      { gemId: "multiple_traps_support", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "spell_totem_support", classes: ["marauder", "scion", "templar", "witch"] },
      { gemId: "stun_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "trap_support", classes: ["duelist", "ranger", "scion", "shadow", "witch"] },
      { gemId: "unbound_ailments_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "void_manipulation_support", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
    ]},
    { act: 1, questName: "자비로운 임무", npc: "네사", rewards: [
      { gemId: "ancestral_call_support", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "arcane_surge_support", classes: ["scion", "shadow", "templar"] },
      { gemId: "chance_to_bleed_support", classes: ["marauder", "ranger", "scion", "templar"] },
      { gemId: "chance_to_poison_support", classes: ["ranger", "scion"] },
      { gemId: "elemental_proliferation_support", classes: ["scion", "shadow", "witch"] },
      { gemId: "infused_channelling_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "mirage_archer_support", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "momentum_support", classes: ["marauder", "duelist", "shadow", "scion", "ranger"] },
      { gemId: "pierce_support", classes: ["duelist", "scion", "shadow", "ranger"] },
      { gemId: "ruthless_support", classes: ["duelist", "scion", "templar"] },
      { gemId: "spell_cascade_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "summon_phantasm_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "swift_assembly_support", classes: ["duelist", "ranger", "scion", "shadow", "witch"] },
      { gemId: "volley_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "witch"] },
    ]},
    { act: 2, questName: "검은 침락자", npc: "예나", rewards: [
      { gemId: "ancestral_cry", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "arcane_cloak", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "arctic_armour", classes: ["duelist", "ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "assassins_mark", classes: ["ranger", "shadow", "duelist", "scion"] },
      { gemId: "blade_blast", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "blood_rage", classes: ["duelist", "marauder", "ranger", "scion", "shadow"] },
      { gemId: "brand_recall", classes: ["marauder", "scion", "templar", "witch"] },
      { gemId: "cold_snap", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "corrupting_fever", classes: ["marauder", "duelist", "scion", "templar"] },
      { gemId: "defiance_banner", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "desecrate", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "divine_retribution", classes: ["templar", "witch", "scion"] },
      { gemId: "ensnaring_arrow", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "eviscerate", classes: ["marauder", "duelist", "templar", "scion"] },
      { gemId: "flesh_and_stone", classes: ["duelist", "marauder", "scion"] },
      { gemId: "forbidden_rite", classes: ["witch", "shadow", "scion"] },
      { gemId: "frenzy", classes: ["duelist", "marauder", "ranger", "scion", "shadow"] },
      { gemId: "galvanic_field", classes: ["shadow", "templar", "witch"] },
      { gemId: "glacial_shield_swipe", classes: ["duelist", "marauder", "ranger", "scion"] },
      { gemId: "herald_of_agony", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "herald_of_ash", classes: [] },
      { gemId: "herald_of_ice", classes: [] },
      { gemId: "herald_of_purity", classes: ["duelist", "marauder", "scion", "templar", "witch"] },
      { gemId: "herald_of_thunder", classes: [] },
      { gemId: "molten_shell", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "poachers_mark", classes: ["shadow", "duelist", "ranger", "scion"] },
      { gemId: "poachers_mark", classes: ["shadow", "duelist", "ranger", "scion"] },
      { gemId: "righteous_fire", classes: ["marauder", "scion", "templar", "witch"] },
      { gemId: "seismic_cry", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "summon_skitterbots", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "swordstorm", classes: ["duelist", "marauder", "scion"] },
      { gemId: "tempest_shield", classes: ["duelist", "marauder", "scion", "shadow", "templar", "witch"] },
    ]},
    { act: 2, questName: "문제의 근원", npc: "예나", rewards: [
      { gemId: "plague_bearer", classes: ["duelist"] },
      { gemId: "bloodlust_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "close_combat_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "cold_to_fire_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "controlled_destruction_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "culling_strike_support", classes: [] },
      { gemId: "damage_on_full_life_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "deadly_ailments_support", classes: ["duelist", "ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "elemental_damage_with_attacks_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "endurance_charge_on_melee_stun_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "faster_casting_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "iron_grip_support", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "iron_will_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "minion_speed_support", classes: ["scion", "templar", "witch"] },
      { gemId: "nightblade_support", classes: ["ranger", "scion", "shadow"] },
      { gemId: "physical_to_lightning_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "point_blank_support", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "power_charge_on_critical_support", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "predator_support", classes: ["scion", "templar", "witch"] },
      { gemId: "rage_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "trap_and_mine_damage_support", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
    ]},
    { act: 2, questName: "날카로운 눈 넓은 시야", npc: "예나", rewards: [
      { gemId: "bloodlust_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "close_combat_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "cold_to_fire_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "concentrated_effect_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "controlled_destruction_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "cruelty_support", classes: ["marauder", "templar", "witch", "scion", "duelist"] },
      { gemId: "culling_strike_support", classes: [] },
      { gemId: "damage_on_full_life_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "deadly_ailments_support", classes: ["duelist", "ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "elemental_damage_with_attacks_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "elemental_focus_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "endurance_charge_on_melee_stun_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "faster_casting_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "fresh_meat_support", classes: ["witch", "templar", "scion"] },
      { gemId: "increased_critical_damage_support", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "iron_grip_support", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "iron_will_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "melee_physical_damage_support", classes: [] },
      { gemId: "minion_life_support", classes: ["scion", "templar", "witch"] },
      { gemId: "minion_speed_support", classes: ["scion", "templar", "witch"] },
      { gemId: "nightblade_support", classes: ["ranger", "scion", "shadow"] },
      { gemId: "overcharge_support", classes: ["ranger", "shadow", "templar", "witch"] },
      { gemId: "physical_to_lightning_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "point_blank_support", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "power_charge_on_critical_support", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "predator_support", classes: ["scion", "templar", "witch"] },
      { gemId: "rage_support", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "sacred_wisps_support", classes: ["ranger", "scion", "templar", "witch"] },
      { gemId: "sadism_support", classes: [] },
      { gemId: "shockwave_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "trap_and_mine_damage_support", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "trinity_support", classes: ["witch", "shadow", "duelist", "ranger", "templar", "scion"] },
      { gemId: "vicious_projectiles_support", classes: ["duelist", "ranger", "scion"] },
      { gemId: "volatility_support", classes: ["marauder", "templar", "duelist", "scion"] },
    ]},
    { act: 3, questName: "떠나보낸 연인", npc: "클라리사", rewards: [
      { gemId: "alchemists_mark", classes: ["ranger", "scion", "shadow"] },
      { gemId: "anger", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "autoexertion", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "automation", classes: [] },
      { gemId: "bane", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "battlemages_cry", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "conductivity", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "despair", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "determination", classes: ["duelist", "marauder", "templar"] },
      { gemId: "discipline", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "dread_banner", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "elemental_weakness", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "energy_blade", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "enfeeble", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "flammability", classes: ["marauder", "scion", "shadow", "templar", "witch"] },
      { gemId: "frostbite", classes: ["scion", "shadow", "templar", "witch", "ranger"] },
      { gemId: "generals_cry", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "grace", classes: ["duelist", "ranger", "shadow"] },
      { gemId: "haste", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "hatred", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "witch"] },
      { gemId: "infernal_cry", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "malevolence", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "petrified_blood", classes: ["marauder", "duelist", "scion", "templar"] },
      { gemId: "plague_bearer", classes: ["ranger", "scion", "shadow"] },
      { gemId: "pride", classes: [] },
      { gemId: "punishment", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "purity_of_elements", classes: [] },
      { gemId: "purity_of_fire", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "purity_of_ice", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "purity_of_lightning", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "rallying_cry", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "spellslinger", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "temporal_chains", classes: ["witch", "scion", "shadow", "ranger"] },
      { gemId: "vengeful_cry", classes: ["duelist", "marauder", "scion"] },
    ]},
    { act: 3, questName: "오른손 절단", npc: "클라리사", rewards: [
      { gemId: "animate_guardian", classes: [] },
      { gemId: "armageddon_brand", classes: ["scion", "templar", "witch"] },
      { gemId: "artillery_ballista", classes: ["duelist", "marauder", "ranger", "scion", "shadow"] },
      { gemId: "ball_lightning", classes: ["shadow", "templar", "witch"] },
      { gemId: "blade_flurry", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "bladefall", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "bladestorm", classes: ["duelist", "marauder", "scion"] },
      { gemId: "blast_rain", classes: ["duelist", "ranger", "scion"] },
      { gemId: "boneshatter", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "charged_dash", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "consecrated_path", classes: ["marauder", "scion", "templar"] },
      { gemId: "crackling_lance", classes: ["shadow", "templar", "witch", "scion"] },
      { gemId: "cremation", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "cyclone", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
      { gemId: "dark_pact", classes: ["scion", "shadow", "witch"] },
      { gemId: "discharge", classes: [] },
      { gemId: "divine_ire", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "dominating_blow", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "earthquake", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "explosive_arrow", classes: ["duelist", "marauder", "ranger"] },
      { gemId: "explosive_concoction", classes: ["duelist", "shadow", "scion", "ranger"] },
      { gemId: "eye_of_winter", classes: ["templar", "shadow", "scion", "witch"] },
      { gemId: "firestorm", classes: ["shadow", "scion", "templar", "witch"] },
      { gemId: "flameblast", classes: ["marauder", "scion", "shadow", "templar", "witch"] },
      { gemId: "flamethrower_trap", classes: ["scion", "shadow", "witch"] },
      { gemId: "glacial_cascade", classes: ["shadow", "templar", "witch", "scion"] },
      { gemId: "hexblast", classes: ["shadow", "templar", "witch", "scion"] },
      { gemId: "ice_crash", classes: ["duelist", "marauder", "ranger", "scion", "shadow", "templar"] },
      { gemId: "ice_trap", classes: ["scion", "shadow", "witch"] },
      { gemId: "kinetic_blast", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "lancing_steel", classes: ["duelist", "ranger", "scion"] },
      { gemId: "lightning_conduit", classes: ["shadow", "witch", "templar"] },
      { gemId: "lightning_spire_trap", classes: ["scion", "shadow", "witch"] },
      { gemId: "penance_brand", classes: ["scion", "templar", "witch"] },
      { gemId: "pestilent_strike", classes: ["ranger", "scion", "shadow"] },
      { gemId: "pyroclast_mine", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "rage_vortex", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "raise_spectre", classes: ["scion", "templar", "witch"] },
      { gemId: "reap", classes: ["marauder", "templar", "witch", "scion", "shadow"] },
      { gemId: "scourge_arrow", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "seismic_trap", classes: ["scion", "shadow", "witch"] },
      { gemId: "shock_nova", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "shockwave_totem", classes: ["marauder", "templar", "witch"] },
      { gemId: "soulrend", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "storm_rain", classes: ["duelist", "shadow", "scion", "ranger"] },
      { gemId: "stormbind", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "summon_reaper", classes: ["witch", "templar", "scion"] },
      { gemId: "tectonic_slam", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "tornado_shot", classes: ["duelist", "ranger", "scion", "shadow"] },
    ]},
    { act: 3, questName: "오른손 절단", npc: "마라모아", rewards: [
      { gemId: "spectral_shield_throw", classes: ["duelist", "marauder", "ranger", "scion", "templar"] },
    ]},
    { act: 4, questName: "봉인 해제", npc: "페타루스와 바냐", rewards: [
      { gemId: "ambush", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "berserk", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "destructive_link", classes: ["scion", "shadow", "witch"] },
      { gemId: "flame_link", classes: ["scion", "marauder", "templar", "duelist"] },
      { gemId: "frost_shield", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "frozen_legion", classes: ["duelist", "marauder", "templar", "scion"] },
      { gemId: "hydrosphere", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "immortal_call", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "intuitive_link", classes: ["duelist", "shadow", "ranger", "scion"] },
      { gemId: "phase_run", classes: ["duelist", "ranger", "scion", "shadow"] },
      { gemId: "protective_link", classes: ["scion", "marauder", "templar"] },
      { gemId: "sigil_of_power", classes: ["witch", "templar", "shadow", "scion"] },
      { gemId: "snipe", classes: ["duelist", "shadow", "scion", "ranger"] },
      { gemId: "soul_link", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "summon_carrion_golem", classes: ["ranger", "scion", "shadow", "templar", "witch"] },
      { gemId: "summon_chaos_golem", classes: [] },
      { gemId: "summon_flame_golem", classes: [] },
      { gemId: "summon_ice_golem", classes: [] },
      { gemId: "summon_lightning_golem", classes: [] },
      { gemId: "summon_stone_golem", classes: [] },
      { gemId: "temporal_rift", classes: ["scion", "shadow", "ranger", "witch"] },
      { gemId: "tornado", classes: ["ranger", "scion", "shadow"] },
      { gemId: "vampiric_link", classes: ["scion", "duelist", "ranger"] },
      { gemId: "void_sphere", classes: ["witch", "templar", "shadow", "scion"] },
    ]},
    { act: 4, questName: "영원한 악몽", npc: "페타루스와 바냐", rewards: [
      { gemId: "arcanist_brand", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "barrage_support", classes: [] },
      { gemId: "behead_support", classes: ["templar", "scion", "marauder", "duelist"] },
      { gemId: "bonechill_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "brutality_support", classes: ["duelist", "marauder", "scion"] },
      { gemId: "cast_on_critical_strike_support", classes: [] },
      { gemId: "cast_on_death_support", classes: [] },
      { gemId: "cast_on_melee_kill_support", classes: [] },
      { gemId: "cast_when_damage_taken_support", classes: [] },
      { gemId: "cast_when_stunned_support", classes: [] },
      { gemId: "cast_while_channelling_support", classes: [] },
      { gemId: "chain_support", classes: [] },
      { gemId: "cluster_traps_support", classes: ["ranger", "scion", "shadow", "witch"] },
      { gemId: "decay_support", classes: ["scion", "shadow", "witch"] },
      { gemId: "eternal_blessing_support", classes: ["duelist", "marauder", "templar", "scion"] },
      { gemId: "fist_of_war_support", classes: ["duelist", "marauder", "scion", "templar"] },
      { gemId: "frigid_bond_support", classes: ["scion", "templar", "witch"] },
      { gemId: "greater_multiple_projectiles_support", classes: [] },
      { gemId: "greater_volley_support", classes: [] },
      { gemId: "hex_bloom_support", classes: ["witch", "shadow", "scion"] },
      { gemId: "hextouch_support", classes: [] },
      { gemId: "ignite_proliferation_support", classes: ["scion", "templar", "witch"] },
      { gemId: "immolate_support", classes: ["marauder", "scion", "templar", "witch"] },
      { gemId: "increased_area_of_effect_support", classes: [] },
      { gemId: "mark_on_hit_support", classes: [] },
      { gemId: "minefield_support", classes: ["scion", "shadow", "witch"] },
      { gemId: "multiple_totems_support", classes: [] },
      { gemId: "multistrike_support", classes: [] },
      { gemId: "overexertion_support", classes: ["marauder", "templar", "duelist", "scion"] },
      { gemId: "returning_projectiles_support", classes: [] },
      { gemId: "rupture_support", classes: ["ranger", "marauder", "templar", "duelist", "scion"] },
      { gemId: "spell_echo_support", classes: [] },
      { gemId: "spellblade_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "trauma_support", classes: ["marauder", "duelist", "templar", "scion"] },
      { gemId: "unleash_support", classes: ["scion", "shadow", "templar", "witch"] },
      { gemId: "vile_toxins_support", classes: ["ranger", "scion", "shadow"] },
      { gemId: "withering_touch_support", classes: ["duelist", "ranger", "scion", "shadow"] },
    ]},
  ],
};